import Head from 'next/head'
import Header from '../components/Header'
import TodoList from '../components/TodoList'
import { useState } from 'react';

export default function Home() {
  const [isLightMode, setIsLightMode] = useState(true);
  return (
    <div className={`${!isLightMode && 'bg-dark_blue'} h-screen`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header mode={isLightMode} changeMode={setIsLightMode} />
      <TodoList mode={isLightMode} />
    </div>
  )
}
